<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Bundles\Blism.Bundle.Languages.Wpf\Blism.Bundle.Languages.Wpf.csproj"/>
		<ProjectReference Include="..\..\Themes\Blism.Theme.DefaultDark\Blism.Theme.DefaultDark.csproj"/>
	</ItemGroup>

</Project>
